version: "3"

services:
  bff-offer:
    build:
      context: ./backend/bff-offer/
      target: "base"
    environment:
      - MONGO_URI=mongodb://mongodb/offers
    command: sh -c "yarn && yarn start:dev"
    container_name: bff-offer
    ports:
      - 3001:3001
    volumes:
      - ${PWD}/backend/bff-offer:/app
    privileged: true
    restart: always
  design-system:
    build:
      context: ./frontend/design-system/
      target: "base"
    command: sh -c "yarn && yarn dev"
    container_name: design-system
    ports:
      - 8081:8081
    volumes:
      - ${PWD}/frontend/design-system:/app
      - ${PWD}/tsconfig.json:/app/tsconfig.json
      - ${PWD}/jest.config.ts:/app/jest.config.ts
    privileged: true
    restart: always
  offer:
    build:
      context: ./frontend/offer/
      target: "base"
    command: sh -c "yarn && yarn dev"
    container_name: offer
    ports:
      - 8080:8080
    volumes:
      - ${PWD}/frontend/offer:/app
      - ${PWD}/tsconfig.json:/app/tsconfig.json
      - ${PWD}/jest.config.ts:/app/jest.config.ts
      - ${PWD}/../../shared/infra:/app/infra
    privileged: true
    restart: always
  shell:
    build:
      context: ./frontend/shell/
      target: "base"
    command: sh -c "yarn && yarn dev"
    container_name: shell
    ports:
      - 3000:3000
    volumes:
      - ${PWD}/frontend/shell:/app
      - ${PWD}/tsconfig.json:/app/tsconfig.json
      - ${PWD}/jest.config.ts:/app/jest.config.ts
    privileged: true
    restart: always
  home:
    build:
      context: ./frontend/home/
      target: "base"
    command: sh -c "yarn && yarn dev"
    container_name: home
    ports:
      - 8082:8082
    volumes:
      - ${PWD}/frontend/home:/app
      - ${PWD}/tsconfig.json:/app/tsconfig.json
      - ${PWD}/jest.config.ts:/app/jest.config.ts
    privileged: true
    restart: always
  shared-infra:
    build:
      context: ./shared/infra/
      target: "base"
    command: sh -c "yarn && yarn dev"
    container_name: shared-infra
    ports:
      - 8083:8083
    volumes:
      - ${PWD}/shared/infra:/app
      - ${PWD}/tsconfig.json:/app/tsconfig.json
    privileged: true
    restart: always
  mongodb:
    build:
      context: ./mongodb/
    container_name: mongodb
    ports:
      - 27017:27017
    privileged: true
    restart: always
networks:
  case-net:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16
